---
title: "Extended Language Network | 08_supplemental_LangfROIs_p.001"
author: "Agata Wolna [`awolna@mit.edu`], Aaron Wright [`aawva@mit.edu`]"
date: "2025-09-25"
format: html
---

## Environment

```{r}
library(tidyverse)
library(here)
library(lme4)

source(here("scripts", "plotting_aesthetics.R")) # EvLab contrast aesthetics
```

## Data

```{r}
# Read in the data for p.001 parcels
parcels=read.delim(here("data", "recode_parcels.txt"), sep = "\t") %>% as_tibble()
data_p001=read.delim(here("data", "detail_gss_p.001.txt"), sep = "\t") %>% as_tibble() %>%
  left_join(parcels) %>% filter(thr=="p.001", parcels == "GcSS")

data_p001 %>% ungroup() %>% select(task, localizer, Subject) %>% unique() %>% count(task, localizer)

# Run statistical models
gcssroi_excluded=c(9, 29, 30, 31, 32, 33)
dat_gcss=data_p001 %>% mutate(condition = as.factor(condition), task=as.factor(task)) %>% filter(!(ROI%in%gcssroi_excluded))

contrasts(dat_gcss$condition) = contr.treatment(2)
contrasts(dat_gcss$task) <- contr.treatment(3, base = 1)

rois=dat_gcss$ROI %>% unique()
tasks=c("Alice", "Lang", "MD")

#### ---- A model testing all tasks together in each ROI ---- ####
roi_models_gcss_all=tibble(matrix(ncol = 7, nrow = 0))
roi_models_gcss_all_means=tibble(matrix(ncol = 8, nrow = 0))
emm_options(lmerTest.limit = 5000)
emm_options(pbkrtest.limit = 5000)
for(i in rois){
  # Model testing differences between conditions
  model_gcss_roi_contrast = lmer(EffectSize ~ 1 + condition + task + condition: task +
                                   (1 | Subject), data = dat_gcss %>% filter(parcels=="GcSS", ROI == i, localizer=="Lang"), control=lmerControl(optimizer = "bobyqa"))
  sum=summary(model_gcss_roi_contrast)$coef 
  names=rownames(sum)
  sum=cbind(names, sum, i) %>% as_tibble()
  roi_models_gcss_all = roi_models_gcss_all %>% rbind(sum)
  
  ## post-hoc comparisons for plots 
  emm <- emmeans(model_gcss_roi_contrast, ~ task * condition)
  means <- emm %>% as.data.frame() %>% cbind(i)
  roi_models_gcss_all_means <- roi_models_gcss_all_means %>% rbind(means)
}
colnames(roi_models_gcss_all_means) <- c('task', 'condition', 'emmean', 'se', 'df', 'lowCI', 'highCI', 'roi')

#### ---- Plot results by ROI ---- ####
# Read in parcel decoding files
# parcels=read.delim("recode_parcels.txt", sep = "\t") %>% rename(roi=ROI)
# parcels=read.delim(here("data", "recode_parcels.txt"), sep = "\t") %>% as_tibble()

effects <- data.frame(
  column1 = c("Alice", "Lang", "MD", "Alice", "Lang", "MD"),
  column2 = c("baseline", "baseline", "baseline", "critical", "critical", "critical"),
  column3 = c("degraded speech", "nonwords", "easy vWM", "intact speech", "sentences", "hard vWM"))

colnames(effects) <- c("task", "condition", "effect")


#### Bar plots for p.001 ####
# percent of participants with reliable responses for each ROI
percent_used = data_p001 %>% filter(LocalizerSize==0) %>% select(ROI, Subject) %>% unique() %>% 
  group_by(ROI) %>% count() %>% mutate(n_all=772) %>% mutate(percent = 100-(n/n_all*100)) %>% rename(roi=ROI) %>% 
  select(-n, -n_all)

roi_models_gcss_all_means = roi_models_gcss_all_means %>% as_tibble() %>% left_join(percent_used) %>% mutate(percent = ifelse(is.na(percent), 100, percent))

means_plots_p001 = roi_models_gcss_all_means %>% left_join(effects) %>% left_join(parcels %>% rename(roi=ROI)) %>% mutate(thr = "p.001", atlas = "GSS") %>% 
  mutate(task = ifelse(task == "Lang", "Reading language", ifelse(task == "Alice", "Auditory language", ifelse(task == "MD", "Spatial WM", NA))))

labels=means_plots_p001 %>% select(ROI_new, hemisphere, label) %>% filter(!is.na(ROI_new)) %>% arrange(ROI_new) %>% unique()

means_plots_p001$effect = factor(means_plots_p001$effect, c("sentences", "nonwords", "intact speech", "degraded speech", "hard vWM", "easy vWM"))
means_plots_p001$label = factor(means_plots_p001$label, labels$label %>% unique())
means_plots_p001$task = factor(means_plots_p001$task, c("Reading language", "Auditory language", "Spatial WM"))

## By ROI GcSS
dir.create(here("viz", "images", "supplemental", "by_roi", "LangfROIs_p.001"), recursive = TRUE, showWarnings = FALSE)
for(nroi in 1:27){
  # Create insets text
  inset_text <- means_plots_p001 %>% filter(ROI_new == nroi) %>% distinct(percent) %>%
    mutate(line = sprintf("%.0f%% of participants", percent)) %>% pull(line) %>% paste(collapse = "\n")
  
  means_plots_p001 %>% filter(ROI_new==nroi) %>% 
    ggplot(aes(x = task, y=emmean, ymin=lowCI, ymax=highCI, fill=effect)) +
    geom_col(position = position_dodge(0.9), color="black", size=0.25) +
    geom_errorbar(position=position_dodge(0.9), linewidth=0.25, width=0) +
    scale_fill_manual(values=cols_fill) +
    scale_y_continuous('Effect size') +
    scale_x_discrete("", labels=NULL) +
    guides(fill = FALSE, size = FALSE) +
    #facet_grid(~hemisphere, scales="free_x") +
    ggtitle(str_c(labels$hemisphere[nroi], "\n", labels$label[nroi])) +
    coord_cartesian(ylim=c(-0.5, 4.2)) +
    annotate("label", x = Inf, y = Inf, label = inset_text, hjust = 1.05, vjust = 1.1, size = 3) +
    my_theme_text_smaller
  ggsave(here("viz", "images", "supplemental", "by_roi", "LangfROIs_p.001", str_c("GCSS_language_alice_md_", nroi, "_roi_nolegend.pdf")), dpi=500, width = 4.8, height = 5, units = "cm")
}

#### Bar plots comparing the top10 fROIs with p.001 fROIs ---- #####
# merge the df for full and n86 models, adding the model as a groupping variable
means_plots_top10=read.delim(here("results", "stats", "gss_n772_model_stats", "gss_n772_roi_models_all_means.txt")) %>% as_tibble() %>% mutate(percent=100) 
means_plots_top10 = means_plots_top10 %>% left_join(effects) %>% left_join(parcels %>% rename(roi = ROI)) %>% mutate(thr="top10%") %>% 
  mutate(task = ifelse(task == "Lang", "Reading language", ifelse(task == "Alice", "Auditory language", ifelse(task == "MD", "Spatial WM", NA))))

means_all_thr_comparison=rbind(means_plots_p001, means_plots_top10)

labels=means_all_thr_comparison %>% select(ROI_new, hemisphere, label) %>% filter(!is.na(ROI_new)) %>% arrange(ROI_new) %>% unique()

means_all_thr_comparison$effect = factor(means_all_thr_comparison$effect, c("sentences", "nonwords", "intact speech", "degraded speech", "hard vWM", "easy vWM"))
means_all_thr_comparison$label = factor(means_all_thr_comparison$label, labels$label %>% unique())
means_all_thr_comparison$task = factor(means_all_thr_comparison$task, c("Reading language", "Auditory language", "Spatial WM"))

## By ROI GcSS
dir.create(here("viz", "images", "supplemental", "by_roi", "LangfROIs_top10_p.001_comparison"), recursive = TRUE, showWarnings = FALSE)
for(nroi in 23:27){
  inset_text <-  means_all_thr_comparison %>% filter(ROI_new == nroi, thr=="p.001") %>% distinct(thr, percent) %>%
    mutate(label = sprintf("%.0f%% of data", percent))
  
  means_all_thr_comparison %>% filter(ROI_new==nroi) %>% mutate(thr_annot=ifelse(thr=="p.001", str_c(thr, "\n (", inset_text$label, ")"), thr)) %>% 
    ggplot(aes(x = task, y=emmean, ymin=lowCI, ymax=highCI, fill=effect)) +
    geom_col(position = position_dodge(0.9), color="black", size=0.25) +
    geom_errorbar(position=position_dodge(0.9), linewidth=0.25, width=0) +
    scale_fill_manual(values=cols_fill) +
    scale_y_continuous('Effect size') +
    scale_x_discrete("", labels=NULL) +
    guides(fill = FALSE, size = FALSE) +
    facet_grid(~thr_annot, scales="free_x") +
    ggtitle(str_c(labels$hemisphere[nroi], "\n", labels$label[nroi])) +
    coord_cartesian(ylim=c(-0.5, 2.5)) +
    my_theme_text_smaller_noborders
  ggsave(here("viz", "images", "supplemental", "by_roi", "LangfROIs_top10_p.001_comparison", str_c("GCSS_language_alice_md_", nroi, "_roi_nolegend.pdf")), dpi=500, width = 6.2, height = 5, units = "cm")
}
```


```{r}
### GSS parcels size
gss_size <- read_excel(here("data", "TableResults.xlsx"), sheet="GcSS_ROI_Size_0.001")

selective=c(1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 16, 18, 20, 21, 22, 23, 24, 25, 28)
core=c(1, 2, 3, 6, 11)

## Size selective
gss_size %>% filter(ROI%in%selective) %>% group_by(Subject) %>% 
  summarize(LangSelectiveSize = sum(LocalizerSize)) %>% ungroup() %>% 
  summarize(meanSize=mean(LangSelectiveSize), sd=sd(LangSelectiveSize)) %>% 
  mutate(size_cm3=(meanSize*8)/1000, sd_cm3=(sd*8)/1000)

gss_size %>% filter(ROI%in%selective) %>% group_by(Subject) %>% 
  summarize(LangSelectiveSize = sum(LocalizerSize)) %>% ungroup() %>% 
  ggplot(aes(x = LangSelectiveSize)) + geom_histogram()

## Size core
gss_size %>% filter(ROI%in%core) %>% group_by(Subject) %>% 
  summarize(LangCoreSize = sum(LocalizerSize)) %>% ungroup() %>% 
  summarize(meanSize=mean(LangCoreSize), sd=sd(LangCoreSize)) %>% 
  mutate(size_cm3=(meanSize*8)/1000, sd_cm3=(sd*8)/1000)

gss_size %>% filter(ROI%in%core) %>% group_by(Subject) %>% 
  summarize(LangCoreSize = sum(LocalizerSize)) %>% ungroup() %>% 
  ggplot(aes(x = LangCoreSize)) + geom_histogram()
```